INSERT INTO currencies (country,country_code,currency_code,currency, symbol) VALUES
			('Afghanistan','AF','AFN','Afghani', '؋'),
			('Albania','AL','ALL','Lek', 'Lek'),
			('Algeria','DZ','DZD','Algerian Dinar', 'DA'),
			('American Samoa','AS','USD','US Dollar', '$'),
			('Andorra','AD','EUR','Euro', '€'),
			('Angola','AO','AOA','Kwanza', 'Kz'),
			('Anguilla','AI','XCD','East Caribbean Dollar', '$'),
			('Antigua and Barbuda','AG','XCD','East Caribbean Dollar', '$'),
			('Argentina','AR','ARS','Argentine Peso', '$'),
			('Armenia','AM','AMD','Armenian Dram', '֏'),
			('Aruba','AW','AWG','Aruban Florin', 'ƒ'),
			('Australia','AU','AUD','Australian Dollar', '$'),
			('Austria','AT','EUR','Euro', '€'),
			('Azerbaijan','AZ','AZN','Azerbaijanian Manat', 'ман'),
			('Bahamas','BS','BSD','Bahamian Dollar', '$'),
			('Bahrain','BH','BHD','Bahraini Dinar', 'BD'),
			('Bangladesh','BD','BDT','Taka', '৳'),
			('Barbados','BB','BBD','Barbados Dollar', '$'),
			('Belarus','BY','BYR','Belarussian Ruble', 'p.'),
			('Belgium','BE','EUR','Euro', '€'),
			('Belize','BZ','BZD','Belize Dollar', 'BZ$'),
			('Benin','BJ','XOF','CFA Franc BCEAO', 'CFA'),
			('Bermuda','BM','BMD','Bermudian Dollar', '$'),
			('Bhutan','BT','INR','Indian Rupee', '₹'),
			('Bolivia, Plurinational State of','BO','BOB','Boliviano', '$b'),
			('Bonaire, Sint Eustatius and Saba','BQ','USD','US Dollar', '$'),
			('Bosnia and Herzegovina','BA','BAM','Convertible Mark', 'KM'),
			('Botswana','BW','BWP','Pula', 'P'),
			('Bouvet Island','BV','NOK','Norwegian Krone', 'kr'),
			('Brazil','BR','BRL','Brazilian Real', 'R$'),
			('British Indian Ocean Territory','IO','USD','US Dollar', '$'),
			('Brunei Darussalam','BN','BND','Brunei Dollar', '$'),
			('Bulgaria','BG','BGN','Bulgarian Lev', 'лв'),
			('Burkina Faso','BF','XOF','CFA Franc BCEAO', 'CFA'),
			('Burundi','BI','BIF','Burundi Franc', 'FBu'),
			('Cambodia','KH','KHR','Riel', '៛'),
			('Cameroon','CM','XAF','CFA Franc BEAC', 'FCFA'),
			('Canada','CA','CAD','Canadian Dollar', '$'),
			('Cape Verde','CV','CVE','Cabo Verde Escudo', 'Esc'),
			('Cayman Islands','KY','KYD','Cayman Islands Dollar', '$'),
			('Central African Republic','CF','XAF','CFA Franc BEAC', 'FCFA'),
			('Chad','TD','XAF','CFA Franc BEAC', 'FCFA'),
			('Chile','CL','CLP','Chilean Peso', '$'),
			('China','CN','CNY','Yuan Renminbi', '¥'),
			('Christmas Island','CX','AUD','Australian Dollar', '$'),
			('Cocos (Keeling) Islands','CC','AUD','Australian Dollar', '$'),
			('Colombia','CO','COP','Colombian Peso', '$'),
			('Comoros','KM','KMF','Comoro Franc', 'CF'),
			('Congo','CG','XAF','CFA Franc BEAC', 'FCFA'),
			('Cook Islands','CK','NZD','New Zealand Dollar', '$'),
			('Costa Rica','CR','CRC','Costa Rican Colon','₡'),
			('Croatia','HR','HRK','Croatian Kuna', 'kn'),
			('Cuba','CU','CUP','Cuban Peso', '₱'),
			('Curaçao','CW','ANG','Netherlands Antillean Guilder', 'ƒ'),
			('Cyprus','CY','EUR','Euro', '€'),
			('Czech Republic','CZ','CZK','Czech Koruna', 'Kč'),
			('Côte d''Ivoire','CI','XOF','CFA Franc BCEAO', 'CFA'),
			('Denmark','DK','DKK','Danish Krone', 'kr'),
			('Djibouti','DJ','DJF','Djibouti Franc', 'Fdj'),
			('Dominica','DM','XCD','East Caribbean Dollar', '$'),
			('Dominican Republic','DO','DOP','Dominican Peso', 'RD$'),
			('Ecuador','EC','USD','US Dollar', '$'),
			('Egypt','EG','EGP','Egyptian Pound', '£'),
			('El Salvador','SV','USD','US Dollar', '$'),
			('Equatorial Guinea','GQ','XAF','CFA Franc BEAC', 'FCFA'),
			('Eritrea','ER','ERN','Nakfa', 'Nkf'),
			('Estonia','EE','EUR','Euro', '€'),
			('Ethiopia','ET','ETB','Ethiopian Birr', 'Br'),
			('Falkland Islands (Malvinas)','FK','FKP','Falkland Islands Pound', '£'),
			('Faroe Islands','FO','DKK','Danish Krone', 'kr'),
			('Fiji','FJ','FJD','Fiji Dollar', '$'),
			('Finland','FI','EUR','Euro', '€'),
			('France','FR','EUR','Euro', '€'),
			('French Guiana','GF','EUR','Euro', '€'),
			('French Polynesia','PF','XPF','CFP Franc', '₣'),
			('French Southern Territories','TF','EUR','Euro', '€'),
			('Gabon','GA','XAF','CFA Franc BEAC', 'FCFA'),
			('Gambia','GM','GMD','Dalasi', 'D'),
			('Georgia','GE','GEL','Lari', 'ლ'),
			('Germany','DE','EUR','Euro', '€'),
			('Ghana','GH','GHS','Ghana Cedi', 'GH₵'),
			('Gibraltar','GI','GIP','Gibraltar Pound', '£'),
			('Greece','GR','EUR','Euro', '€'),
			('Greenland','GL','DKK','Danish Krone', 'kr'),
			('Grenada','GD','XCD','East Caribbean Dollar', '$'),
			('Guadeloupe','GP','EUR','Euro', '€'),
			('Guam','GU','USD','US Dollar', '$'),
			('Guatemala','GT','GTQ','Quetzal', 'Q'),
			('Guernsey','GG','GBP','Pound Sterling', '£'),
			('Guinea','GN','GNF','Guinea Franc', 'FG'),
			('Guinea-Bissau','GW','XOF','CFA Franc BCEAO', 'CFA'),
			('Guyana','GY','GYD','Guyana Dollar', '$'),
			('Haiti','HT','USD','US Dollar', '$'),
			('Heard Island and McDonald Islands','HM','AUD','Australian Dollar', '$'),
			('Holy See (Vatican City State)','VA','EUR','Euro', '€'),
			('Honduras','HN','HNL','Lempira', 'L'),
			('Hong Kong','HK','HKD','Hong Kong Dollar', '$'),
			('Hungary','HU','HUF','Forint', 'Ft'),
			('Iceland','IS','ISK','Iceland Krona', 'kr'),
			('India','IN','INR','Indian Rupee', '₹'),
			('Indonesia','ID','IDR','Rupiah', 'Rp'),
			('Iran, Islamic Republic of','IR','IRR','Iranian Rial', '﷼'),
			('Iraq','IQ','IQD','Iraqi Dinar', 'ع.د'),
			('Ireland','IE','EUR','Euro', '€'),
			('Isle of Man','IM','GBP','Pound Sterling', '£'),
			('Israel','IL','ILS','New Israeli Sheqel', '₪'),
			('Italy','IT','EUR','Euro', '€'),
			('Jamaica','JM','JMD','Jamaican Dollar', 'J$'),
			('Japan','JP','JPY','Yen', '¥'),
			('Jersey','JE','GBP','Pound Sterling', '£'),
			('Jordan','JO','JOD','Jordanian Dinar', 'د.ا'),
			('Kazakhstan','KZ','KZT','Tenge', 'лв'),
			('Kenya','KE','KES','Kenyan Shilling', 'Ksh'),
			('Kiribati','KI','AUD','Australian Dollar', '$'),
			('Korea, Democratic People''s Republic of','KP','KPW','North Korean Won', '₩'),
			('Korea, Republic of','KR','KRW','Won','₩'),
			('Kuwait','KW','KWD','Kuwaiti Dinar', 'د.ك'),
			('Kyrgyzstan','KG','KGS','Som', 'лв'),
			('Lao People''s Democratic Republic','LA','LAK','Kip', '₭'),
			('Latvia','LV','EUR','Euro', '€'),
			('Lebanon','LB','LBP','Lebanese Pound', '£'),
			('Lesotho','LS','ZAR','Rand', 'R'),
			('Liberia','LR','LRD','Liberian Dollar', '$'),
			('Libya','LY','LYD','Libyan Dinar', 'ل.د'),
			('Liechtenstein','LI','CHF','Swiss Franc', 'CHF'),
			('Lithuania','LT','EUR','Euro', '€'),
			('Luxembourg','LU','EUR','Euro', '€'),
			('Macao','MO','MOP','Pataca', 'MOP$'),
			('Macedonia, the Former Yugoslav Republic of','MK','MKD','Denar', 'ден'),
			('Madagascar','MG','MGA','Malagasy Ariary', 'Ar'),
			('Malawi','MW','MWK','Kwacha', 'MK'),
			('Malaysia','MY','MYR','Malaysian Ringgit', 'RM'),
			('Maldives','MV','MVR','Rufiyaa', 'Rf'),
			('Mali','ML','XOF','CFA Franc BCEAO', 'CFA'),
			('Malta','MT','EUR','Euro', '€'),
			('Marshall Islands','MH','USD','US Dollar', '$'),
			('Martinique','MQ','EUR','Euro', '€'),
			('Mauritania','MR','MRO','Ouguiya', 'UM'),
			('Mauritius','MU','MUR','Mauritius Rupee', '₨'),
			('Mayotte','YT','EUR','Euro', '€'),
			('Mexico','MX','MXN','Mexican Peso', '$'),
			('Micronesia, Federated States of','FM','USD','US Dollar', '$'),
			('Moldova, Republic of','MD','MDL','Moldovan Leu', 'L'),
			('Monaco','MC','EUR','Euro', '€'),
			('Mongolia','MN','MNT','Tugrik', '₮'),
			('Montenegro','ME','EUR','Euro', '€'),
			('Montserrat','MS','XCD','East Caribbean Dollar','$'),
			('Morocco','MA','MAD','Moroccan Dirham','MAD'),
			('Mozambique','MZ','MZN','Mozambique Metical', 'MT'),
			('Myanmar','MM','MMK','Kyat', 'K'),
			('Namibia','NA','ZAR','Rand', 'R'),
			('Nauru','NR','AUD','Australian Dollar', '$'),
			('Nepal','NP','NPR','Nepalese Rupee', '₨'),
			('Netherlands','NL','EUR','Euro', '€'),
			('New Caledonia','NC','XPF','CFP Franc', '₣'),
			('New Zealand','NZ','NZD','New Zealand Dollar', '$'),
			('Nicaragua','NI','NIO','Cordoba Oro', 'C$'),
			('Niger','NE','XOF','CFA Franc BCEAO', 'CFA'),
			('Nigeria','NG','NGN','Naira', '₦'),
			('Niue','NU','NZD','New Zealand Dollar', '$'),
			('Norfolk Island','NF','AUD','Australian Dollar', '$'),
			('Northern Mariana Islands','MP','USD','US Dollar', '$'),
			('Norway','NO','NOK','Norwegian Krone', 'kr'),
			('Oman','OM','OMR','Rial Omani', '﷼'),
			('Pakistan','PK','PKR','Pakistan Rupee', '₨'),
			('Palau','PW','USD','US Dollar','$'),
			('Panama','PA','USD','US Dollar', '$'),
			('Papua New Guinea','PG','PGK','Kina', 'K'),
			('Paraguay','PY','PYG','Guarani', 'Gs'),
			('Peru','PE','PEN','Nuevo Sol', 'S/.'),
			('Philippines','PH','PHP','Philippine Peso','Php'),
			('Pitcairn','PN','NZD','New Zealand Dollar','$'),
			('Poland','PL','PLN','Zloty', 'zł'),
			('Portugal','PT','EUR','Euro', '€'),
			('Puerto Rico','PR','USD','US Dollar', '$'),
			('Qatar','QA','QAR','Qatari Rial', '﷼'),
			('Romania','RO','RON','New Romanian Leu', 'lei'),
			('Russian Federation','RU','RUB','Russian Ruble', 'руб'),
			('Rwanda','RW','RWF','Rwanda Franc', 'R₣'),
			('Réunion','RE','EUR','Euro', '€'),
			('Saint Barthélemy','BL','EUR','Euro', '€'),
			('Saint Helena, Ascension and Tristan da Cunha','SH','SHP','Saint Helena Pound', '£'),
			('Saint Kitts and Nevis','KN','XCD','East Caribbean Dollar', '$'),
			('Saint Lucia','LC','XCD','East Caribbean Dollar', '$'),
			('Saint Martin (French part)','MF','EUR','Euro', '€'),
			('Saint Pierre and Miquelon','PM','EUR','Euro', '€'),
			('Saint Vincent and the Grenadines','VC','XCD','East Caribbean Dollar', '$'),
			('Samoa','WS','WST','Tala', 'WS$'),
			('San Marino','SM','EUR','Euro', '€'),
			('Sao Tome and Principe','ST','STD','Dobra', 'Db'),
			('Saudi Arabia','SA','SAR','Saudi Riyal', '﷼'),
			('Senegal','SN','XOF','CFA Franc BCEAO', 'CFA'),
			('Serbia','RS','RSD','Serbian Dinar', 'Дин.'),
			('Seychelles','SC','SCR','Seychelles Rupee', '₨'),
			('Sierra Leone','SL','SLL','Leone', 'Le'),
			('Singapore','SG','SGD','Singapore Dollar', '$'),
			('Sint Maarten (Dutch part)','SX','ANG','Netherlands Antillean Guilder', 'ƒ'),
			('Slovakia','SK','EUR','Euro', '€'),
			('Slovenia','SI','EUR','Euro', '€'),
			('Solomon Islands','SB','SBD','Solomon Islands Dollar', '$'),
			('Somalia','SO','SOS','Somali Shilling', 'S'),
			('South Africa','ZA','ZAR','Rand', 'R'),
			('South Sudan','SS','SSP','South Sudanese Pound', '£'),
			('Spain','ES','EUR','Euro', '€'),
			('Sri Lanka','LK','LKR','Sri Lanka Rupee', '₨'),
			('Sudan','SD','SDG','Sudanese Pound', 'ج.س'),
			('Suriname','SR','SRD','Surinam Dollar', '$'),
			('Svalbard and Jan Mayen','SJ','NOK','Norwegian Krone', 'kr'),
			('Swaziland','SZ','SZL','Lilangeni', 'L'),
			('Sweden','SE','SEK','Swedish Krona', 'kr'),
			('Switzerland','CH','CHF','Swiss Franc', 'CHF'),
			('Syrian Arab Republic','SY','SYP','Syrian Pound', '£'),
			('Taiwan, Province of China','TW','TWD','New Taiwan Dollar', 'NT$'),
			('Tajikistan','TJ','TJS','Somoni', 'ЅM'),
			('Tanzania, United Republic of','TZ','TZS','Tanzanian Shilling', 'TSh'),
			('Thailand','TH','THB','Baht', '฿'),
			('Timor-Leste','TL','USD','US Dollar', '$'),
			('Togo','TG','XOF','CFA Franc BCEAO', 'CFA'),
			('Tokelau','TK','NZD','New Zealand Dollar', '$'),
			('Tonga','TO','TOP','Pa’anga', 'T$'),
			('Trinidad and Tobago','TT','TTD','Trinidad and Tobago Dollar', 'TT$'),
			('Tunisia','TN','TND','Tunisian Dinar', 'DT'),
			('Turkey','TR','TRY','Turkish Lira', '₺'),
			('Turkmenistan','TM','TMT','Turkmenistan New Manat', 'T'),
			('Turks and Caicos Islands','TC','USD','US Dollar', '$'),
			('Tuvalu','TV','AUD','Australian Dollar', '$'),
			('Uganda','UG','UGX','Uganda Shilling', 'USh'),
			('Ukraine','UA','UAH','Hryvnia', '₴'),
			('United Arab Emirates','AE','AED','UAE Dirham', 'د.إ'),
			('United Kingdom','GB','GBP','Pound Sterling', '£'),
			('United States','US','USD','US Dollar', '$'),
			('United States Minor Outlying Islands','UM','USD','US Dollar', '$'),
			('Uruguay','UY','UYU','Peso Uruguayo', '$U'),
			('Uzbekistan','UZ','UZS','Uzbekistan Sum', 'лв'),
			('Vanuatu','VU','VUV','Vatu', 'VT'),
			('Venezuela, Bolivarian Republic of','VE','VEF','Bolivar', 'Bs'),
			('Viet Nam','VN','VND','Dong', '₫'),
			('Virgin Islands, British','VG','USD','US Dollar', '$'),
			('Virgin Islands, U.S.','VI','USD','US Dollar', '$'),
			('Wallis and Futuna','WF','XPF','CFP Franc', '₣'),
			('Western Sahara','EH','MAD','Moroccan Dirham', 'MAD'),
			('Yemen','YE','YER','Yemeni Rial', '﷼'),
			('Zambia','ZM','ZMW','Zambian Kwacha', 'ZK'),
			('Zimbabwe','ZW','ZWL','Zimbabwe Dollar', '$'),
			('Åland Islands','AX','EUR','Euro', '€');